<link rel="stylesheet" href="/static/res/bs/css/bootstrap.css"/>
<link rel="stylesheet" href="/static/res/bs/css/bootstrap-table.min.css">
<link rel="stylesheet" href="/static/res/bs/css/bootstrap-table-fixed-columns.css">
<link rel="stylesheet" href="/static/res/jquery/jquery-ui.css"/>
<link rel="stylesheet" href="/static/res/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="/static/res/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="/static/res/AdminLTE/dist/css/AdminLTE.min.css">
<link rel="stylesheet" href="/static/res/AdminLTE/dist/css/skins/_all-skins.min.css">
<link rel="stylesheet" href="/static/res/AdminLTE/plugins/pace/pace.min.css">
<link rel="stylesheet" href="/static/res/chok/css/chok.view.css">